<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sentry_rclpy</name>
  <version>0.1.0</version>
  <description>A hackweek SDK for RCLPy (ROS client library for Python).</description>
  <author email="alexander.webb@sentry.io">Alexander Alderman Webb</author>
  <maintainer email="alexander.webb@sentry.io">Alexander Alderman Webb</maintainer>
  <license>MIT</license>

  <url type="repository">https://github.com/getsentry/sentry-rclpy</url>
  <url type="bugtracker">https://github.com/getsentry/sentry-rclpy/issues</url>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-sentry-sdk</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
